#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          N4
# Required-Start:    mountvirtfs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Rockchip N4 daemon
### END INIT INFO

case "$1" in
	start)
		echo "starting n4..."
		{ sleep 5; n4; }&
		jobs -p > /var/run/n4.pid
		;;
	stop)
		echo "stoping n4... "
		kill $(cat /var/run/n4.pid) || true
		killall n4 || true
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
