#!/bin/sh
#
# Start logging
#

start() {
	echo "login:"
	echo ""Password:
	echo "Last login: "
}

stop() {
	echo ""
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
