#!/bin/sh
#

lunch_start()
{
	insmod /lib/modules/dw_mmc-rockchip.ko &
	echo "Now we are ready to start your first application" > /dev/kmsg
	rkipc -a /etc/iqfiles -d /dev/video34 -s /dev/v4l-subdev7 &
}

lunch_stop()
{
	echo "All applications have been stopped"
	killall -9 rkipc
}

case "$1" in
	start)
		lunch_start
		;;
	stop)
		lunch_stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
