#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          frecon
# Required-Start:    mountvirtfs
# Required-Stop:
# Should-Start:
# Should-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: frecon daemon
### END INIT INFO

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

case "$1" in
	start)
		echo -n "starting frecon... "
		frecon --daemon --enable-vts
		echo "done."
		;;
	stop)
		echo -n "stoping frecon... "
		killall frecon
		echo "done."
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
esac

exit 0
