RKIIO_SITE = $(TOPDIR)/../external/rkiio

RKIIO_SITE_METHOD = local

RKIIO_INSTALL_STAGING = YES

RKIIO_CONF_OPTS = -DWARNINGS_AS_ERRORS=ON

ifeq ($(BR2_PACKAGE_RKIIO_SANITIZER_DYNAMIC), y)
RKIIO_CONF_OPTS += -DSANITIZER_DYNAMIC=ON
else
ifeq ($(BR2_PACKAGE_RKIIO_SANITIZER_STATIC), y)
RKIIO_CONF_OPTS += -DSANITIZER_STATIC=ON
endif
endif

ifeq ($(BR2_PACKAGE_RK_OEM), y)
RKIIO_TARGET_DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR)
define RKIIO_INSTALL_TARGET_REMOVE_HOOK
	rm -rf $(RKIIO_TARGET_DESTDIR)/usr/include
	rm -rf $(RKIIO_TARGET_DESTDIR)/usr/lib/pkgconfig
endef
RKIIO_POST_INSTALL_TARGET_HOOKS += RKIIO_INSTALL_TARGET_REMOVE_HOOK
RKIIO_DEPENDENCIES += rk_oem
RKIIO_CONF_OPTS += -DCONFIG_OEM=1
RKIIO_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
endif

$(eval $(cmake-package))
